url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Swisherrz
email: Swisherrrz@gmail.com
description: A full view of where I am on social media!


# Team names, titles and social links


- name: Swisherrz
  pic: 3
 
  social:
    - title: twitter
      url: # Twitter.com/Swisherrz
    - title: facebook
      url: #
    - title: google-plus
      url: #



# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
